trigger:
  branches:
    include:
      - adf_publish
    exclude:
      - dev
      - feature/*

pool:
  vmImage: "ubuntu-18.04"

stages:
  - stage: release
    displayName: Release
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/adf_publish'))
    jobs:
      - job: hello
        steps:
          - task: Bash@3
            displayName: echo hello
            inputs:
              targetType: inline
              script: >
                echo "Hello World!"
            condition: always()
          - task: AzureResourceGroupDeployment@2
            inputs:
              azureSubscription: "SandboxSC"
              action: "Create Or Update Resource Group"
              resourceGroupName: "sbox-adamadf-dev-rg"
              location: "West Europe"
              templateLocation: "Linked artifact"
              csmFile: "$(Build.SourcesDirectory)/sboxadamadfdev/ARMTemplateForFactory.json"
              csmParametersFile: "$(Build.SourcesDirectory)/sboxadamadfdev/ARMTemplateParametersForFactory.json"
              overrideParameters: "-factoryName adamtestadf2"
              deploymentMode: "Incremental"
