trigger:
  branches:
    include:
      - adf_publish
    exclude:
      - dev
      - feature/*

pool:
  vmImage: "ubuntu-18.04"

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: hello
        steps:
          - task: Bash@3
            displayName: echo hello
            inputs:
              targetType: inline
              script: >
                echo "Hello World!"
            condition: always()
  - stage: release
    displayName: Release
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/adf_publish'))
    jobs:
      - job: hello
        steps:
          - task: Bash@3
            displayName: echo hello
            inputs:
              targetType: inline
              script: >
                echo "Hello World!"
            condition: always()
